feat(scully): Adds ability to pass an http agent to the jsonRoute plugin
scullyio/scully pull request #1371
Opened 2021-05-27 00:53 UTC by tenoriojuann

- This change will allow the an agent to be able to use a proxy behind a corporate proxy

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Node's Http Agent is not supported

Issue Number: #1355 

## What is the new behavior?

Passing any Http Proxy Agent is now supported to get around corporate proxies

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2021-05-27 16:43 UTC, tenoriojuann commented
Hi,

I am getting errors on files that were not touched. How can I resolve those issues ?

2021-05-29 03:35 UTC, SanderElias requested changes

2021-05-29 03:35 UTC, SanderElias commented on libs/scully/package.json
> +  "version": "1.1.2",
Please, don't touch the versions, those are controlled by tooling

2021-05-29 03:36 UTC, SanderElias commented
@tenoriojuann Thanks for the PR, we had an issue with Githib and the CLI, that should be fixed now.
Please merge main, , remove the version tock, and I can merge this.

2021-05-29 07:16 UTC, SanderElias approved these changes

2021-05-29 11:07 UTC, merged