docs: add manual installation instructions
scullyio/scully pull request #1385
Opened 2021-06-06 09:38 UTC by mainawycliffe

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Other... Please describe: Docs Update 

## What is the current behavior?

Add Manual Installation Instruction For Scully

Closes #1359 and Closes #878

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2021-06-06 11:45 UTC, mainawycliffe commented
@SanderElias should I add instructions to create the plugins directory as well?

2021-06-07 18:13 UTC, Jefiozie requested changes
Hi, @mainawycliffe I've made some suggestions to your PR, would you mind providing me with feedback if these are valid changes? If you agree with the changes would you be willing to change them in this PR?

2021-06-07 18:13 UTC, Jefiozie commented on docs/learn/getting-started/installation.md
> +**NB:** You can pass configurations to the `ScullLibModule` using the `forRoot`
```suggestion
**NB:** You can pass configurations to the `ScullyLibModule` using the `forRoot`
```

2021-06-07 18:13 UTC, Jefiozie commented on docs/learn/getting-started/installation.md
> +First, install both `@scullyio/scully` and `@scullyio/ng-lib` npm packages
```suggestion
First, install the following packages `@scullyio/scully` and `@scullyio/ng-lib`
```

2021-06-07 18:13 UTC, Jefiozie commented on docs/learn/getting-started/installation.md
> +And finally, create a `scully.[PROJECT_NAME].config.ts`, replacing
```suggestion
Finally, create a `scully.[PROJECT_NAME].config.ts`, replacing
```

2021-06-07 18:13 UTC, Jefiozie commented on docs/learn/getting-started/installation.md
> +content of the Scully config file like shown below:
```suggestion
`[PROJECT_NAME]`, with the name of your Angular project. Then add the
content of the Scully config file like shown below:
```

2021-06-07 18:31 UTC, mainawycliffe commented
No, problem, I will take care of the changes.

2021-06-08 06:01 UTC, SanderElias commented
@mainawycliffe Thanks for writing this! it is well needed. 
Still, I would love it even slightly more if the manual installation was in a separate document. 
A `manualInstallation.md` next to the file where it is now would do quite nicely.

2021-06-08 06:54 UTC, mainawycliffe commented
@SanderElias Yeah, that makes sense. Will make the change.

2021-06-08 17:26 UTC, SanderElias approved these changes

2021-06-08 18:15 UTC, Jefiozie approved these changes
LGTM

2021-06-09 12:33 UTC, merged