Write a the spanish translation of docs\community\starters.md
scullyio/scully pull request #1416
Opened 2021-08-05 13:08 UTC by AlexScigalszky

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: Write a the spanish translation of docs\community\starters.md

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-08-06 03:00 UTC, SanderElias submitted a review, later dismissed
LGTM, but as I don't understand spanish, I'm going to ask @aaronfrost to check the content

2021-09-13 23:12 UTC, Villanuevand commented
@SanderElias  I'll take a look...

2021-09-14 15:17 UTC, Villanuevand requested changes
@AlexScigalszky
I just made some comments about words to change...

Let me know anything else ... 
Great work here, thanks for the support.

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Obtendra un sitio para ventas online simple y funcional con todos tus productos, ejecutandose en Internet.
```suggestion
Obtén un sitio para ventas online simple y funcional con todos tus productos, ejecutandose en Internet.
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Con unos pocos clics puedes deployar tu proyecto en Netlify!
```suggestion
Con unos pocos clics puedes desplegar tu proyecto en Netlify!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Con unos pocos clics puedes deployar tu proyecto en Netlify!
```suggestion
Con unos pocos clics puedes desplegar tu proyecto en Netlify!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Confligura tu blog de cocina en unos simples pasos y comparte esas maravillosas recetas con el mundo!
```suggestion
Configura tu blog de cocina en algunos simples pasos y comparte tus maravillosas recetas con el mundo!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Con unos pocos clics puedes deployar tu proyecto en Netlify!
```suggestion
Con unos pocos clics puedes desplegar tu proyecto en Netlify!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Crea tus proyectos con Sculy y Flotiq y muestralos con todas las personas del alrededor del mundo!
```suggestion
Crea tus proyectos con Scully y Flotiq y muéstralos
 a otros alrededor del mundo!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Con unos pocos clics puedes deployar tu proyecto en Netlify!
```suggestion
Con unos pocos clics puedes desplegar tu proyecto en Netlify!
```

2021-09-14 15:17 UTC, Villanuevand commented on docs/community/starters_es.md
> +Con unos pocos clics puedes deployar tu proyecto en Netlify!
```suggestion
Con unos pocos clics puedes desplegar tu proyecto en Netlify!
```

2021-09-17 11:47 UTC, AlexScigalszky commented
@Villanuevand  thanks it looks better!

2021-09-17 13:22 UTC, Villanuevand approved these changes
LGTM! 

Thanks @AlexScigalszky  for your support. 

To get this PR merged you need to update this branch.

2021-09-24 09:05 UTC, merged